name: CI - Inventory Service

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine Docker Image Tag
        id: docker_tag
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=unknown" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          TAG=latest
          if [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            TAG=dev
          fi
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:${{ env.TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:${{ env.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:${{ env.TAG }}

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:${{ env.TAG }}
