name: CI - Inventory Service

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine Docker Image Tag
        id: docker_tag
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=unknown" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            # main 브랜치에서는 latest 태그와 함께 푸시
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest
          
            # 만약 태그 푸시라면, 해당 버전 태그도 함께 푸시
            if [[ $GITHUB_REF == refs/tags/v* ]]; then
              TAG=${GITHUB_REF#refs/tags/}
              docker tag ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:$TAG
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:$TAG
            fi
          
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            # dev 브랜치에서는 dev 태그로 푸시
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:dev .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:dev
          
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            # 태그가 있는 경우 해당 버전으로 푸시
            TAG=${GITHUB_REF#refs/tags/}
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:$TAG .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:$TAG
          fi

