name: PR CI - Inventory Service

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Quick Build Test
        run: ./gradlew build --scan